# Generated by Django 4.2.7 on 2023-11-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="BookId", new_name="book_id",
        ),
    ]
