# Generated by Django 4.2.7 on 2023-11-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_rename_bookid_book_book_id"),
        ("members", "0002_rename_firstname_member_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("for_days", models.IntegerField(blank=True, default=7)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="books.book"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
