# Generated by Django 4.2.7 on 2023-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=40, unique=True)),
                ("firstName", models.CharField(max_length=40)),
                ("lastName", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("phoneNumber", models.CharField(max_length=15)),
            ],
        ),
    ]
