# Generated by Django 4.2.7 on 2023-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member", old_name="firstName", new_name="first_name",
        ),
        migrations.RenameField(
            model_name="member", old_name="lastName", new_name="last_name",
        ),
        migrations.RenameField(
            model_name="member", old_name="phoneNumber", new_name="phone_number",
        ),
        migrations.AddField(
            model_name="member", name="dues", field=models.IntegerField(default=0),
        ),
    ]
